=encoding utf8

=head1 NAME

bootstrap/README.pod - bootstrapping plan

=head1 OVERVIEW

Ωη;)XD is bootstrapped from OMeta/JS (using node.js). All bootstrap stages use
the same grammar files for their sources (*.dual). The differences between
JavaScript and Winxed are bridged using the C pre-processor as well as
language-specific headers and footers maintained in separate files (capo and
coda).

There are 3 bootstrap stages:

=over

=item stage0

An Ωη;)XD compiler in JavaScript, created by C<ojsc> (the OMeta/JS compiler)

=item stage1

An Ωη;)XD compiler in Winxed, created by C<Ωηc.js> (wrapper around stage0)

=item stage2

An Ωη;)XD compiler in Winxed, created by C<ometac.winxed> (wrapper around stage1)

=back

=cut
